/* The following code was generated by JFlex 1.4.3 on 20/02/16 14:19 */

package tirke.cupPlugin.parser;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.TokenType;
import static tirke.cupPlugin.psi.CupTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 20/02/16 14:19 from the specification file
 * <tt>/Users/Tirke/Downloads/Cup support/src/tirke/cupPlugin/CupLexer.flex</tt>
 */
public class CupLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int OPT_JAVA_CODE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\4\1\1\22\0\1\3\4\0\1\42"+
    "\4\0\1\7\1\0\1\13\1\0\1\16\1\6\12\5\1\11\1\17"+
    "\1\0\1\12\3\0\1\44\1\5\1\47\1\51\1\52\4\5\1\43"+
    "\4\5\1\50\6\5\1\45\4\5\4\0\1\46\1\0\1\22\1\5"+
    "\1\20\1\36\1\34\1\41\1\33\1\40\1\24\1\5\1\32\1\21"+
    "\1\25\1\35\1\27\1\26\1\5\1\30\1\23\1\31\2\5\1\37"+
    "\3\5\1\14\1\10\1\15\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\3\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\1\1\10\1\11\12\3\1\1\1\3\2\12"+
    "\2\0\1\13\2\0\1\14\1\15\16\3\1\0\1\3"+
    "\1\16\2\0\1\17\15\3\1\20\1\3\1\0\1\3"+
    "\1\0\1\13\1\3\1\21\1\22\1\3\1\23\3\3"+
    "\1\24\7\3\1\25\1\0\1\3\1\13\1\26\1\3"+
    "\1\27\5\3\1\30\3\3\1\31\1\3\1\32\1\33"+
    "\1\34\1\3\1\35\5\3\1\36\6\3\1\37\1\40"+
    "\4\3\1\41\1\42\1\3\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\126\0\254\0\327\0\u0102"+
    "\0\126\0\126\0\u012d\0\126\0\u0158\0\126\0\126\0\u0183"+
    "\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db"+
    "\0\u0306\0\u0331\0\u035c\0\126\0\u0387\0\254\0\u03b2\0\u03dd"+
    "\0\u0408\0\u0433\0\126\0\126\0\u045e\0\u0489\0\u04b4\0\u04df"+
    "\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637"+
    "\0\u0662\0\u068d\0\u06b8\0\u06e3\0\126\0\u070e\0\u0739\0\126"+
    "\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866\0\u0891"+
    "\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968\0\u0993\0\u09be\0\u09e9"+
    "\0\u0a14\0\u0a3f\0\u070e\0\u0a6a\0\327\0\327\0\u0a95\0\327"+
    "\0\u0ac0\0\u0aeb\0\u0b16\0\327\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2"+
    "\0\u0bed\0\u0c18\0\u0c43\0\327\0\u0c6e\0\u0c99\0\126\0\327"+
    "\0\u0cc4\0\327\0\u0cef\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b\0\327"+
    "\0\u0dc6\0\u0df1\0\u0e1c\0\126\0\u0e47\0\327\0\327\0\327"+
    "\0\u0e72\0\327\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\327"+
    "\0\u0f74\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\327\0\327"+
    "\0\u1076\0\u10a1\0\u10cc\0\u10f7\0\327\0\327\0\u1122\0\327";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\5\1\7\1\10\1\11"+
    "\1\12\1\13\1\3\1\14\1\15\1\3\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\7\1\25\1\7"+
    "\1\26\1\27\3\7\1\30\1\7\1\31\2\7\1\32"+
    "\1\33\7\7\11\34\1\35\41\34\55\0\1\5\53\0"+
    "\1\36\2\0\1\37\51\0\1\7\12\0\22\7\1\0"+
    "\10\7\6\0\1\40\1\41\54\0\1\42\3\0\1\43"+
    "\46\0\1\44\46\0\1\7\12\0\1\7\1\45\5\7"+
    "\1\46\12\7\1\0\10\7\5\0\1\7\12\0\14\7"+
    "\1\47\5\7\1\0\10\7\5\0\1\7\12\0\1\50"+
    "\21\7\1\0\10\7\5\0\1\7\12\0\1\51\10\7"+
    "\1\52\10\7\1\0\10\7\5\0\1\7\12\0\5\7"+
    "\1\53\7\7\1\54\4\7\1\0\10\7\5\0\1\7"+
    "\12\0\2\7\1\55\5\7\1\56\11\7\1\0\10\7"+
    "\5\0\1\7\12\0\4\7\1\57\15\7\1\0\10\7"+
    "\5\0\1\7\12\0\14\7\1\60\5\7\1\0\10\7"+
    "\5\0\1\7\12\0\7\7\1\61\12\7\1\0\10\7"+
    "\5\0\1\7\12\0\4\7\1\62\15\7\1\0\10\7"+
    "\26\0\1\63\31\0\1\7\12\0\22\7\1\0\1\7"+
    "\1\64\6\7\15\0\1\65\43\0\1\40\44\0\2\40"+
    "\1\0\50\40\7\66\1\67\43\66\12\0\1\70\45\0"+
    "\1\7\12\0\2\7\1\71\17\7\1\0\10\7\5\0"+
    "\1\7\12\0\16\7\1\72\3\7\1\0\10\7\5\0"+
    "\1\7\12\0\21\7\1\73\1\0\10\7\5\0\1\7"+
    "\12\0\11\7\1\74\10\7\1\0\10\7\5\0\1\7"+
    "\12\0\2\7\1\75\17\7\1\0\10\7\5\0\1\7"+
    "\12\0\2\7\1\76\17\7\1\0\10\7\5\0\1\7"+
    "\12\0\6\7\1\77\13\7\1\0\10\7\5\0\1\7"+
    "\12\0\4\7\1\100\15\7\1\0\10\7\5\0\1\7"+
    "\12\0\1\101\7\7\1\102\11\7\1\0\10\7\5\0"+
    "\1\7\12\0\14\7\1\103\5\7\1\0\10\7\5\0"+
    "\1\7\12\0\13\7\1\104\6\7\1\0\10\7\5\0"+
    "\1\7\12\0\10\7\1\105\11\7\1\0\10\7\5\0"+
    "\1\7\12\0\15\7\1\106\4\7\1\0\10\7\5\0"+
    "\1\7\12\0\11\7\1\107\10\7\1\0\10\7\30\0"+
    "\1\110\27\0\1\7\12\0\22\7\1\0\2\7\1\111"+
    "\5\7\7\66\1\112\51\66\1\113\1\112\43\66\5\0"+
    "\1\7\12\0\3\7\1\114\16\7\1\0\10\7\5\0"+
    "\1\7\12\0\14\7\1\115\5\7\1\0\10\7\5\0"+
    "\1\7\12\0\11\7\1\116\10\7\1\0\10\7\5\0"+
    "\1\7\12\0\4\7\1\117\15\7\1\0\10\7\5\0"+
    "\1\7\12\0\15\7\1\120\4\7\1\0\10\7\5\0"+
    "\1\7\12\0\10\7\1\121\1\122\10\7\1\0\10\7"+
    "\5\0\1\7\12\0\7\7\1\123\12\7\1\0\10\7"+
    "\5\0\1\7\12\0\11\7\1\124\10\7\1\0\10\7"+
    "\5\0\1\7\12\0\12\7\1\125\7\7\1\0\10\7"+
    "\5\0\1\7\12\0\3\7\1\126\16\7\1\0\10\7"+
    "\5\0\1\7\12\0\1\127\21\7\1\0\10\7\5\0"+
    "\1\7\12\0\20\7\1\130\1\7\1\0\10\7\5\0"+
    "\1\7\12\0\5\7\1\131\14\7\1\0\10\7\5\0"+
    "\1\7\12\0\2\7\1\132\6\7\1\133\10\7\1\0"+
    "\10\7\5\0\1\7\12\0\20\7\1\134\1\7\1\0"+
    "\10\7\34\0\1\135\23\0\1\7\12\0\22\7\1\0"+
    "\1\7\1\136\6\7\6\66\1\137\1\112\43\66\5\0"+
    "\1\7\12\0\3\7\1\140\16\7\1\0\10\7\5\0"+
    "\1\7\12\0\7\7\1\141\12\7\1\0\10\7\5\0"+
    "\1\7\12\0\11\7\1\142\10\7\1\0\10\7\5\0"+
    "\1\7\12\0\4\7\1\143\15\7\1\0\10\7\5\0"+
    "\1\7\12\0\10\7\1\144\11\7\1\0\10\7\5\0"+
    "\1\7\12\0\2\7\1\145\17\7\1\0\10\7\5\0"+
    "\1\7\12\0\14\7\1\146\5\7\1\0\10\7\5\0"+
    "\1\7\12\0\14\7\1\147\5\7\1\0\10\7\5\0"+
    "\1\7\12\0\11\7\1\150\10\7\1\0\10\7\5\0"+
    "\1\7\12\0\4\7\1\151\15\7\1\0\10\7\5\0"+
    "\1\7\12\0\3\7\1\152\16\7\1\0\10\7\5\0"+
    "\1\7\12\0\14\7\1\153\5\7\1\0\10\7\20\0"+
    "\1\154\37\0\1\7\12\0\22\7\1\0\3\7\1\155"+
    "\4\7\5\0\1\7\12\0\15\7\1\156\4\7\1\0"+
    "\10\7\5\0\1\7\12\0\1\157\21\7\1\0\10\7"+
    "\5\0\1\7\12\0\11\7\1\160\10\7\1\0\10\7"+
    "\5\0\1\7\12\0\13\7\1\161\6\7\1\0\10\7"+
    "\5\0\1\7\12\0\10\7\1\162\11\7\1\0\10\7"+
    "\5\0\1\7\12\0\16\7\1\163\3\7\1\0\10\7"+
    "\5\0\1\7\12\0\15\7\1\164\4\7\1\0\10\7"+
    "\5\0\1\7\12\0\3\7\1\165\16\7\1\0\10\7"+
    "\5\0\1\7\12\0\10\7\1\166\11\7\1\0\10\7"+
    "\5\0\1\7\12\0\22\7\1\0\4\7\1\167\3\7"+
    "\5\0\1\7\12\0\14\7\1\170\5\7\1\0\10\7"+
    "\5\0\1\7\12\0\14\7\1\171\5\7\1\0\10\7"+
    "\5\0\1\7\12\0\2\7\1\172\17\7\1\0\10\7"+
    "\5\0\1\7\12\0\7\7\1\173\12\7\1\0\10\7"+
    "\5\0\1\7\12\0\5\7\1\174\14\7\1\0\10\7"+
    "\5\0\1\7\12\0\22\7\1\0\5\7\1\175\2\7"+
    "\5\0\1\7\12\0\15\7\1\176\4\7\1\0\10\7"+
    "\5\0\1\7\12\0\1\7\1\177\20\7\1\0\10\7"+
    "\5\0\1\7\12\0\1\200\21\7\1\0\10\7\5\0"+
    "\1\7\12\0\4\7\1\201\15\7\1\0\10\7\5\0"+
    "\1\7\12\0\22\7\1\0\6\7\1\202\1\7\5\0"+
    "\1\7\12\0\1\203\21\7\1\0\10\7\5\0\1\7"+
    "\12\0\15\7\1\204\4\7\1\0\10\7\5\0\1\7"+
    "\12\0\22\7\1\0\7\7\1\205\5\0\1\7\12\0"+
    "\14\7\1\206\5\7\1\0\10\7\5\0\1\7\12\0"+
    "\2\7\1\207\17\7\1\0\10\7\5\0\1\7\12\0"+
    "\1\7\1\210\20\7\1\0\10\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4429];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\3\1\2\11\1\1\1\11"+
    "\1\1\2\11\14\1\1\11\1\1\2\0\1\1\2\0"+
    "\2\11\16\1\1\0\1\1\1\11\2\0\1\11\17\1"+
    "\1\0\1\1\1\0\22\1\1\0\1\1\1\11\14\1"+
    "\1\11\34\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CupLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return INIT;
          }
        case 36: break;
        case 25: 
          { return PERCENT_PREC;
          }
        case 37: break;
        case 7: 
          { return COMMA;
          }
        case 38: break;
        case 32: 
          { return NONASSOC;
          }
        case 39: break;
        case 24: 
          { return RIGHT;
          }
        case 40: break;
        case 19: 
          { return SCAN;
          }
        case 41: break;
        case 31: 
          { return TERMINAL;
          }
        case 42: break;
        case 11: 
          { return COMMENT;
          }
        case 43: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 44: break;
        case 5: 
          { return BAR;
          }
        case 45: break;
        case 3: 
          { return IDENTIFIER;
          }
        case 46: break;
        case 10: 
          { yybegin(OPT_JAVA_CODE); return JAVA;
          }
        case 47: break;
        case 34: 
          { return PRECED;
          }
        case 48: break;
        case 29: 
          { return PARSER;
          }
        case 49: break;
        case 9: 
          { return SEMI;
          }
        case 50: break;
        case 16: 
          { return NON;
          }
        case 51: break;
        case 2: 
          { return TokenType.WHITE_SPACE;
          }
        case 52: break;
        case 26: 
          { return ACTION;
          }
        case 53: break;
        case 6: 
          { return COLON;
          }
        case 54: break;
        case 15: 
          { return CCEQ;
          }
        case 55: break;
        case 12: 
          { return  RIGHTCUPBRACES;
          }
        case 56: break;
        case 33: 
          { return JAVA_CODE;
          }
        case 57: break;
        case 17: 
          { return CODE;
          }
        case 58: break;
        case 23: 
          { return START;
          }
        case 59: break;
        case 27: 
          { return STATIC;
          }
        case 60: break;
        case 35: 
          { return NONTERMINAL;
          }
        case 61: break;
        case 28: 
          { return IMPORT;
          }
        case 62: break;
        case 13: 
          { yybegin(OPT_JAVA_CODE); return  LEFTCUPBRACES;
          }
        case 63: break;
        case 22: 
          { return CLASS;
          }
        case 64: break;
        case 18: 
          { return LEFT;
          }
        case 65: break;
        case 14: 
          { yybegin(YYINITIAL); yypushback(yylength());
          }
        case 66: break;
        case 8: 
          { return DOT;
          }
        case 67: break;
        case 21: 
          { return WITH;
          }
        case 68: break;
        case 30: 
          { return PACKAGE;
          }
        case 69: break;
        case 4: 
          { return STAR;
          }
        case 70: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
