/* The following code was generated by JFlex 1.4.3 on 23/02/16 23:43 */

package tirke.cupPlugin.parser;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.TokenType;
import static tirke.cupPlugin.psi.CupTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 23/02/16 23:43 from the specification file
 * <tt>/Users/Tirke/Downloads/Cup support/src/tirke/cupPlugin/parser/CupLexer.flex</tt>
 */
public class CupLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int OPT_JAVA_CODE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\4\0\1\41"+
    "\4\0\1\6\1\0\1\12\1\0\1\15\1\5\12\4\1\10\1\16"+
    "\1\0\1\11\3\0\1\43\1\4\1\46\1\50\1\51\4\4\1\42"+
    "\4\4\1\47\6\4\1\44\4\4\4\0\1\45\1\0\1\21\1\4"+
    "\1\17\1\35\1\33\1\40\1\32\1\37\1\23\1\4\1\31\1\20"+
    "\1\24\1\34\1\26\1\25\1\4\1\27\1\22\1\30\2\4\1\36"+
    "\3\4\1\13\1\7\1\14\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\1\1\10\1\11\12\3\1\1\1\3\2\12"+
    "\1\13\2\0\1\14\1\15\16\3\1\0\1\3\1\16"+
    "\1\0\1\17\15\3\1\20\1\3\1\0\1\3\1\21"+
    "\1\3\1\22\1\23\1\3\1\24\3\3\1\25\7\3"+
    "\1\26\1\0\1\3\1\27\1\3\1\30\5\3\1\31"+
    "\3\3\1\32\1\3\1\33\1\34\1\35\1\3\1\36"+
    "\5\3\1\37\6\3\1\40\1\41\4\3\1\42\1\43"+
    "\1\3\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\124\0\250\0\322\0\124"+
    "\0\124\0\374\0\124\0\u0126\0\124\0\124\0\u0150\0\u017a"+
    "\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca"+
    "\0\u02f4\0\u031e\0\124\0\u0348\0\u0372\0\u039c\0\u03c6\0\124"+
    "\0\124\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec"+
    "\0\u0516\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612\0\u063c"+
    "\0\u0666\0\124\0\u0690\0\124\0\u06ba\0\u06e4\0\u070e\0\u0738"+
    "\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0834\0\u085e\0\u0888"+
    "\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a\0\124\0\u0984\0\250"+
    "\0\250\0\u09ae\0\250\0\u09d8\0\u0a02\0\u0a2c\0\250\0\u0a56"+
    "\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28\0\u0b52\0\250\0\u0b7c"+
    "\0\u0ba6\0\250\0\u0bd0\0\250\0\u0bfa\0\u0c24\0\u0c4e\0\u0c78"+
    "\0\u0ca2\0\250\0\u0ccc\0\u0cf6\0\u0d20\0\124\0\u0d4a\0\250"+
    "\0\250\0\250\0\u0d74\0\250\0\u0d9e\0\u0dc8\0\u0df2\0\u0e1c"+
    "\0\u0e46\0\250\0\u0e70\0\u0e9a\0\u0ec4\0\u0eee\0\u0f18\0\u0f42"+
    "\0\250\0\250\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\250\0\250"+
    "\0\u1014\0\250";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\3\1\13\1\14\1\3\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\6\1\24\1\6\1\25\1\26"+
    "\3\6\1\27\1\6\1\30\2\6\1\31\1\32\7\6"+
    "\10\33\1\34\41\33\54\0\1\5\53\0\1\6\12\0"+
    "\22\6\1\0\10\6\5\0\1\35\1\36\53\0\1\37"+
    "\3\0\1\40\45\0\1\41\45\0\1\6\12\0\1\6"+
    "\1\42\5\6\1\43\12\6\1\0\10\6\4\0\1\6"+
    "\12\0\14\6\1\44\5\6\1\0\10\6\4\0\1\6"+
    "\12\0\1\45\21\6\1\0\10\6\4\0\1\6\12\0"+
    "\1\46\10\6\1\47\10\6\1\0\10\6\4\0\1\6"+
    "\12\0\5\6\1\50\7\6\1\51\4\6\1\0\10\6"+
    "\4\0\1\6\12\0\2\6\1\52\5\6\1\53\11\6"+
    "\1\0\10\6\4\0\1\6\12\0\4\6\1\54\15\6"+
    "\1\0\10\6\4\0\1\6\12\0\14\6\1\55\5\6"+
    "\1\0\10\6\4\0\1\6\12\0\7\6\1\56\12\6"+
    "\1\0\10\6\4\0\1\6\12\0\4\6\1\57\15\6"+
    "\1\0\10\6\25\0\1\60\30\0\1\6\12\0\22\6"+
    "\1\0\1\6\1\61\6\6\14\0\1\62\35\0\2\35"+
    "\1\0\47\35\6\36\1\63\43\36\11\0\1\64\44\0"+
    "\1\6\12\0\2\6\1\65\17\6\1\0\10\6\4\0"+
    "\1\6\12\0\16\6\1\66\3\6\1\0\10\6\4\0"+
    "\1\6\12\0\21\6\1\67\1\0\10\6\4\0\1\6"+
    "\12\0\11\6\1\70\10\6\1\0\10\6\4\0\1\6"+
    "\12\0\2\6\1\71\17\6\1\0\10\6\4\0\1\6"+
    "\12\0\2\6\1\72\17\6\1\0\10\6\4\0\1\6"+
    "\12\0\6\6\1\73\13\6\1\0\10\6\4\0\1\6"+
    "\12\0\4\6\1\74\15\6\1\0\10\6\4\0\1\6"+
    "\12\0\1\75\7\6\1\76\11\6\1\0\10\6\4\0"+
    "\1\6\12\0\14\6\1\77\5\6\1\0\10\6\4\0"+
    "\1\6\12\0\13\6\1\100\6\6\1\0\10\6\4\0"+
    "\1\6\12\0\10\6\1\101\11\6\1\0\10\6\4\0"+
    "\1\6\12\0\15\6\1\102\4\6\1\0\10\6\4\0"+
    "\1\6\12\0\11\6\1\103\10\6\1\0\10\6\27\0"+
    "\1\104\26\0\1\6\12\0\22\6\1\0\2\6\1\105"+
    "\5\6\5\36\1\106\1\63\43\36\4\0\1\6\12\0"+
    "\3\6\1\107\16\6\1\0\10\6\4\0\1\6\12\0"+
    "\14\6\1\110\5\6\1\0\10\6\4\0\1\6\12\0"+
    "\11\6\1\111\10\6\1\0\10\6\4\0\1\6\12\0"+
    "\4\6\1\112\15\6\1\0\10\6\4\0\1\6\12\0"+
    "\15\6\1\113\4\6\1\0\10\6\4\0\1\6\12\0"+
    "\10\6\1\114\1\115\10\6\1\0\10\6\4\0\1\6"+
    "\12\0\7\6\1\116\12\6\1\0\10\6\4\0\1\6"+
    "\12\0\11\6\1\117\10\6\1\0\10\6\4\0\1\6"+
    "\12\0\12\6\1\120\7\6\1\0\10\6\4\0\1\6"+
    "\12\0\3\6\1\121\16\6\1\0\10\6\4\0\1\6"+
    "\12\0\1\122\21\6\1\0\10\6\4\0\1\6\12\0"+
    "\20\6\1\123\1\6\1\0\10\6\4\0\1\6\12\0"+
    "\5\6\1\124\14\6\1\0\10\6\4\0\1\6\12\0"+
    "\2\6\1\125\6\6\1\126\10\6\1\0\10\6\4\0"+
    "\1\6\12\0\20\6\1\127\1\6\1\0\10\6\33\0"+
    "\1\130\22\0\1\6\12\0\22\6\1\0\1\6\1\131"+
    "\6\6\4\0\1\6\12\0\3\6\1\132\16\6\1\0"+
    "\10\6\4\0\1\6\12\0\7\6\1\133\12\6\1\0"+
    "\10\6\4\0\1\6\12\0\11\6\1\134\10\6\1\0"+
    "\10\6\4\0\1\6\12\0\4\6\1\135\15\6\1\0"+
    "\10\6\4\0\1\6\12\0\10\6\1\136\11\6\1\0"+
    "\10\6\4\0\1\6\12\0\2\6\1\137\17\6\1\0"+
    "\10\6\4\0\1\6\12\0\14\6\1\140\5\6\1\0"+
    "\10\6\4\0\1\6\12\0\14\6\1\141\5\6\1\0"+
    "\10\6\4\0\1\6\12\0\11\6\1\142\10\6\1\0"+
    "\10\6\4\0\1\6\12\0\4\6\1\143\15\6\1\0"+
    "\10\6\4\0\1\6\12\0\3\6\1\144\16\6\1\0"+
    "\10\6\4\0\1\6\12\0\14\6\1\145\5\6\1\0"+
    "\10\6\17\0\1\146\36\0\1\6\12\0\22\6\1\0"+
    "\3\6\1\147\4\6\4\0\1\6\12\0\15\6\1\150"+
    "\4\6\1\0\10\6\4\0\1\6\12\0\1\151\21\6"+
    "\1\0\10\6\4\0\1\6\12\0\11\6\1\152\10\6"+
    "\1\0\10\6\4\0\1\6\12\0\13\6\1\153\6\6"+
    "\1\0\10\6\4\0\1\6\12\0\10\6\1\154\11\6"+
    "\1\0\10\6\4\0\1\6\12\0\16\6\1\155\3\6"+
    "\1\0\10\6\4\0\1\6\12\0\15\6\1\156\4\6"+
    "\1\0\10\6\4\0\1\6\12\0\3\6\1\157\16\6"+
    "\1\0\10\6\4\0\1\6\12\0\10\6\1\160\11\6"+
    "\1\0\10\6\4\0\1\6\12\0\22\6\1\0\4\6"+
    "\1\161\3\6\4\0\1\6\12\0\14\6\1\162\5\6"+
    "\1\0\10\6\4\0\1\6\12\0\14\6\1\163\5\6"+
    "\1\0\10\6\4\0\1\6\12\0\2\6\1\164\17\6"+
    "\1\0\10\6\4\0\1\6\12\0\7\6\1\165\12\6"+
    "\1\0\10\6\4\0\1\6\12\0\5\6\1\166\14\6"+
    "\1\0\10\6\4\0\1\6\12\0\22\6\1\0\5\6"+
    "\1\167\2\6\4\0\1\6\12\0\15\6\1\170\4\6"+
    "\1\0\10\6\4\0\1\6\12\0\1\6\1\171\20\6"+
    "\1\0\10\6\4\0\1\6\12\0\1\172\21\6\1\0"+
    "\10\6\4\0\1\6\12\0\4\6\1\173\15\6\1\0"+
    "\10\6\4\0\1\6\12\0\22\6\1\0\6\6\1\174"+
    "\1\6\4\0\1\6\12\0\1\175\21\6\1\0\10\6"+
    "\4\0\1\6\12\0\15\6\1\176\4\6\1\0\10\6"+
    "\4\0\1\6\12\0\22\6\1\0\7\6\1\177\4\0"+
    "\1\6\12\0\14\6\1\200\5\6\1\0\10\6\4\0"+
    "\1\6\12\0\2\6\1\201\17\6\1\0\10\6\4\0"+
    "\1\6\12\0\1\6\1\202\20\6\1\0\10\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4158];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\2\1\2\11\1\1\1\11"+
    "\1\1\2\11\14\1\1\11\2\1\2\0\2\11\16\1"+
    "\1\0\1\1\1\11\1\0\1\11\17\1\1\0\1\1"+
    "\1\11\21\1\1\0\15\1\1\11\34\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CupLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { return STAR;
          }
        case 37: break;
        case 27: 
          { return ACTION;
          }
        case 38: break;
        case 2: 
          { return TokenType.WHITE_SPACE;
          }
        case 39: break;
        case 36: 
          { return NONTERMINAL;
          }
        case 40: break;
        case 18: 
          { return CODE;
          }
        case 41: break;
        case 32: 
          { return TERMINAL;
          }
        case 42: break;
        case 15: 
          { return CCEQ;
          }
        case 43: break;
        case 20: 
          { return SCAN;
          }
        case 44: break;
        case 7: 
          { return COMMA;
          }
        case 45: break;
        case 8: 
          { return DOT;
          }
        case 46: break;
        case 10: 
          { yybegin(OPT_JAVA_CODE); return JAVA;
          }
        case 47: break;
        case 9: 
          { return SEMI;
          }
        case 48: break;
        case 34: 
          { return JAVA_CODE;
          }
        case 49: break;
        case 16: 
          { return NON;
          }
        case 50: break;
        case 22: 
          { return WITH;
          }
        case 51: break;
        case 13: 
          { yybegin(OPT_JAVA_CODE); return  LEFTCUPBRACES;
          }
        case 52: break;
        case 6: 
          { return COLON;
          }
        case 53: break;
        case 17: 
          { return BLOCK_COMMENT;
          }
        case 54: break;
        case 29: 
          { return IMPORT;
          }
        case 55: break;
        case 12: 
          { return RIGHTCUPBRACES;
          }
        case 56: break;
        case 24: 
          { return START;
          }
        case 57: break;
        case 19: 
          { return LEFT;
          }
        case 58: break;
        case 30: 
          { return PARSER;
          }
        case 59: break;
        case 11: 
          { return LINE_COMMENT;
          }
        case 60: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 61: break;
        case 25: 
          { return RIGHT;
          }
        case 62: break;
        case 23: 
          { return CLASS;
          }
        case 63: break;
        case 21: 
          { return INIT;
          }
        case 64: break;
        case 14: 
          { yybegin(YYINITIAL); yypushback(yylength());
          }
        case 65: break;
        case 31: 
          { return PACKAGE;
          }
        case 66: break;
        case 26: 
          { return PERCENT_PREC;
          }
        case 67: break;
        case 5: 
          { return BAR;
          }
        case 68: break;
        case 28: 
          { return STATIC;
          }
        case 69: break;
        case 3: 
          { return IDENTIFIER;
          }
        case 70: break;
        case 33: 
          { return NONASSOC;
          }
        case 71: break;
        case 35: 
          { return PRECED;
          }
        case 72: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
