# GitHub Actions Workflow created for testing and preparing the plugin release in following steps:
# - validate Gradle Wrapper,
# - run test and verifyPlugin tasks,
# - run buildPlugin task and prepare artifact for the further tests,
# - run IntelliJ Plugin Verifier,
# - create a draft release.
#
# Workflow is triggered on push and pull_request events.

name: Build
on: [ push, pull_request ]
jobs:
  gradleValidation:
    name: Gradle wrapper verification
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2.3.4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

  test:
    name: Test
    needs: gradleValidation
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2.2.0
        with:
          distribution: zulu
          java-version: 11

      - name: Fetch Sources
        uses: actions/checkout@v2.3.4

      - name: Setup Gradle Dep Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Run Linters and Test
        run: ./gradlew check

      - name: Verify Plugin
        run: ./gradlew verifyPlugin